#! /usr/bin/env sh

# Minimize the inputs to XS for testing, passing script args.
# No rc files; no functions from the environment; no history; minimal prompt.

HERE=$(cd `dirname $0`; pwd)
env -i HOME=$HOME \
	strace -f --detach-on=execve --trace=%process,%signal,%desc,%pure \
		--timestamps=format:unix,precision:ns -o xs_strace.log \
		$HERE/build/xs -Zp "$@"
